name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - main

jobs:
  publish_javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
          cache: "gradle"
        name: Setup Java JDK 11
      - name: Execute Permission for .gradlew/
        run: chmod +x gradlew
      - name: Build App (fixes some dependency errors)
        run: ./gradlew build
      - name: Generate Javadoc
        run: ./gradlew generateReleaseJavadoc
      - name: Commit and Push Javadocs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./doc
          git commit -m "Autoupdated Docs"
          git push
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc
